# Generated by Django 5.0.6 on 2024-06-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSeekerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('education', models.CharField(choices=[('highschool', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Ph.D.')], max_length=20)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('experience', models.IntegerField()),
                ('skills', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
            ],
        ),
    ]
