# Generated by Django 5.0.6 on 2024-06-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comments',
            new_name='comment',
        ),
    ]
