# Generated by Django 5.0.6 on 2024-06-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobID',
            field=models.TextField(max_length=255),
        ),
    ]
